
name: 部署文档

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: 安装依赖
        run: |
          npm install hexo-cli -g
          npm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          hexo clean
          hexo generate

      - name: 部署文档到本仓库的gh-pages分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: public

      - name: 部署文档到指定仓库的指定分支
        env:
          TZ: Asia/Shanghai
          # 在私人源码仓库的设置中设置私钥：[SourceRepo]-->Settings-->Setrets-->Actions secrets
          GITHUB_PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKENS_GITHUB }}  
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: public
          token: ${{ secrets.PERSONAL_ACCESS_TOKENS_GITHUB }}
          repository-name: sumumm/sumumm.github.io

